# Generated by Django 4.2 on 2023-04-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Заглавие урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('img_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id картинки')),
                ('url', models.URLField(verbose_name='URL-telegraph урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Id-телеграма')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Псевдоним')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('number', models.CharField(blank=True, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='StatusLesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=False, verbose_name='В избранное')),
                ('started', models.BooleanField(default=False, verbose_name='Урок начат')),
                ('finished', models.BooleanField(default=False, verbose_name='Урок закончен')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_users', to='tg_manage.lesson')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_lessons', to='tg_manage.profile')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='tg_manage.profile', verbose_name='Автор'),
        ),
    ]
