# Generated by Django 4.2 on 2023-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Псевдоним'),
        ),
    ]
