# Generated by Django 4.2 on 2023-04-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='img_id',
            field=models.CharField(blank=True, default='AgACAgIAAxkBAAOlZDBAK24zrhv8PuXvI8Groa-CfGUAAqnFMRvKcIFJoV0paVg5cyQBAAMCAAN4AAMvBA', max_length=200, null=True, verbose_name='Id картинки'),
        ),
    ]
