# Generated by Django 4.2 on 2023-04-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0003_alter_lesson_img_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='img_id',
            new_name='photo_id',
        ),
    ]
