# Generated by Django 4.2 on 2023-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0005_alter_lesson_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='photo_id',
            field=models.URLField(blank=True, default='https://telegra.ph//file/03f446be71d69a87288e6.jpg', null=True, verbose_name='URL картинки'),
        ),
    ]
