# Generated by Django 4.2 on 2023-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0007_theme_alter_statuslesson_unique_together_lessontheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_url', models.URLField(unique=True, verbose_name='URL-изображения')),
                ('category', models.CharField(max_length=100, unique=True, verbose_name='Категория изображения')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
