# Generated by Django 4.2 on 2023-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0008_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория изображения'),
        ),
    ]
