# Generated by Django 4.2 on 2023-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0010_remove_photo_category_photo_type_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(default=' ', max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
