# Generated by Django 4.2 on 2023-04-19 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0012_photopack_remove_photo_category_photo_photo_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephotopack',
            name='photo_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='tg_manage.photopack'),
        ),
        migrations.AlterField(
            model_name='profilephotopack',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_pack', to='tg_manage.profile', unique=True),
        ),
    ]
