# Generated by Django 4.2 on 2023-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_manage', '0013_alter_profilephotopack_photo_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Псевдоним'),
        ),
    ]
